#开发环境配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bookWebSite?serverTimezone=UTC
      username: root
      password: a

  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl